accessKey        = "werwrew"
secretKey        = "wewewrew"
region           = "us-east-1"
api-gateway-name = "vijaycloudnloudgateway"
vpc_cidr         = "10.0.0.0/16"
project          = "duckduckgo"
key-name         = "xps-add"
