accessKey   = "AKIA2VK6KRT7LUTOT7XG"
secretKey   = "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"
region      = "eu-west-1"
lambdaname  = "lambda-aws-ec2-tags-mail-alerts"
fromAddress = "vijay@cloudnloud.com"
